      - name: Tag and push image
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER_LC/expense-tracker-api
          docker tag expense-tracker-api:${{ github.sha }} $IMAGE:${{ github.sha }}
          docker tag expense-tracker-api:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest